# -*- coding: utf-8 -*-
"""contextual recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp7CCZYCDDKpe-Neu1QQHYLBFTtlMYKG
"""

!pip install geopandas

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/MyDrive/CIS 4000/CIS 4000 - Urban Planning/Land_Use (1).csv"
landuse = pd.read_csv(path)

landuse.head()

landuse['c_dig1desc'].unique()

landuse['c_dig1desc'].value_counts(normalize=True).round(3)*100

landuse[['c_dig1desc', 'c_dig2desc']].value_counts().head(10)

import matplotlib.pyplot as plt

code_labels = {
    1: "Residential",
    2: "Commercial",
    3: "Industrial",
    4: "Transportation",
    5: "Cultural/Recreation",
    6: "Utilities",
    7: "Institutional",
    8: "Open Space",
    9: "Vacant",
    10: "Water"
}

counts = landuse['c_dig1'].value_counts().sort_index()
labels = [code_labels.get(i, str(i)) for i in counts.index]


plt.figure(figsize=(10,6))
plt.bar(labels, counts, color='skyblue', edgecolor='black')
plt.title("Distribution of Land Use Types in Philadelphia (2023)", fontsize=14)
plt.xlabel("Land Use Category", fontsize=12)
plt.ylabel("Number of Parcels", fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

landuse[['c_dig1', 'c_dig1desc']].drop_duplicates().sort_values('c_dig1')

area_summary = landuse.groupby('c_dig1desc')['Shape__Area'].sum().sort_values(ascending=False)
area_percent = (area_summary / area_summary.sum() * 100).round(2)

print("Land Use by Total Area (sq meters):\n", area_summary)
print("\nLand Use by Percent of City Area:\n", area_percent)

#   - land use polygons: https://opendataphilly.org/datasets/land-use/
#   - ZIP code boundaries: https://opendataphilly.org/datasets/zip-codes/

# load datasets into GeoDataFrames
#   import geopandas as gpd
#   landuse = gpd.read_file("/content/Land_Use.shp").to_crs(epsg=4326)
#   zipcodes = gpd.read_file("/content/Zip_Codes.shp").to_crs(epsg=4326)

# spatially join to assign ZIP codes to parcels
#   landuse_zip = gpd.sjoin(landuse, zipcodes[["ZIPCODE","geometry"]], how="left", predicate="intersects")

# aggregate by ZIP code
#   summary = (
#       landuse_zip.groupby(["ZIPCODE","c_dig1desc"])["Shape__Area"]
#       .sum()
#       .reset_index()
#   )
#   summary.to_csv("landuse_by_zipcode.csv", index=False)